-- Schema drift fix: remaining d785a10 changes never migrated
--
-- Context: commit d785a10 "feat(accounting): Thai accounting standards
-- audit fixes" (2026-04-06) modified many Prisma models but never ran
-- `prisma migrate dev`. Commit message explicitly says:
--   "Note: C-002 (VAT on hire-purchase interest) deferred ...
--    Requires `prisma migrate dev` after merge."
-- The migrate dev was skipped. Result: partial schema drift across
-- Expense, Repossession, AuditLog, CommissionPayout, TradeIn tables.
--
-- The receipts portion of this drift is addressed in the previous
-- migration (20260411180000_add_receipt_compliance_fields). This
-- migration cleans up everything else.
--
-- Changes mapped to d785a10's critical fixes:
--   C-003 (WHT fields on Expense):         wht_rate, net_payment
--   C-007 (Expense void audit trail):      void_reason, voided_at, voided_by_id
--   R-002 (Repossession cost adjustment):  customer_refund_enabled + 9 others
--   W-011 (AuditLog immutability):         DROP updated_at
--   W-008 (Commission payout tightening):  indexes + default removal
--
-- SQL generated by `prisma migrate diff --from-url <live-db-after-migrate-deploy>
--   --to-schema-datamodel prisma/schema.prisma --script` against a fresh
-- temporary Postgres 16 container with all prior migrations applied.
--
-- Safety review:
--   • Every ADD COLUMN is either nullable or has a DEFAULT → safe on existing rows
--   • customer_refund_enabled uses NOT NULL DEFAULT false — existing rows get false
--   • DROP updated_at on audit_logs is a deliberate W-011 immutability choice
--     (audit records should never mutate; the column was schema-only noise)
--   • trade_ins FK redefinition (CASCADE → SET NULL) matches current schema intent
--     (customer deletion should not cascade to trade-in records)
--   • commission_payouts DEFAULT removals tighten schema — new inserts must
--     supply values explicitly (service code already does so after d785a10)

-- DropForeignKey
ALTER TABLE "trade_ins" DROP CONSTRAINT "trade_ins_customer_id_fkey";

-- AlterTable
ALTER TABLE "audit_logs" DROP COLUMN "updated_at";

-- AlterTable
ALTER TABLE "commission_payouts" ALTER COLUMN "total_sales" DROP DEFAULT,
ALTER COLUMN "total_commission" DROP DEFAULT;

-- AlterTable
ALTER TABLE "expenses" ADD COLUMN     "net_payment" DECIMAL(12,2),
ADD COLUMN     "void_reason" TEXT,
ADD COLUMN     "voided_at" TIMESTAMP(3),
ADD COLUMN     "voided_by_id" TEXT,
ADD COLUMN     "wht_rate" DECIMAL(5,4);

-- AlterTable
ALTER TABLE "repossessions" ADD COLUMN     "closing_amount" DECIMAL(12,2),
ADD COLUMN     "customer_refund" DECIMAL(12,2),
ADD COLUMN     "customer_refund_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "discount_amount" DECIMAL(12,2),
ADD COLUMN     "discount_pct" DECIMAL(5,2),
ADD COLUMN     "finance_cost" DECIMAL(12,2),
ADD COLUMN     "market_value" DECIMAL(12,2),
ADD COLUMN     "profit_loss" DECIMAL(12,2),
ADD COLUMN     "remaining_cost" DECIMAL(12,2),
ADD COLUMN     "remaining_months" INTEGER;

-- CreateIndex
CREATE INDEX "commission_payouts_salesperson_id_idx" ON "commission_payouts"("salesperson_id");

-- CreateIndex
CREATE INDEX "commission_payouts_deleted_at_idx" ON "commission_payouts"("deleted_at");

-- AddForeignKey
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_voided_by_id_fkey" FOREIGN KEY ("voided_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trade_ins" ADD CONSTRAINT "trade_ins_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE SET NULL ON UPDATE CASCADE;
