import { describe, it, expect } from 'vitest';
import {
  apiMethodToWizard,
  draftFingerprint,
  draftToFormValues,
  isAutoGeneratedRef,
  type PaymentDraftRow,
} from '../draftHydration';

const baseDraft: PaymentDraftRow = {
  id: 'd-1',
  amount: '1515.83',
  paymentMethod: 'BANK_TRANSFER',
  depositAccountCode: '11-1201',
  lateFee: '50',
  lateFeeWaiverAmount: '25',
  lateFeeWaiverReasonCode: 'loyal_customer',
  waiverApproverId: 'u-approver',
  consumeAdvance: true,
  paidDate: '2026-07-08T17:00:00.000Z', // = 2026-07-09 00:00 BKK
  paymentCase: 'NORMAL',
  transactionRef: 'KBANK-XYZ-001',
  evidenceUrl: 'https://s3/slips/abc.jpg',
  notes: 'ลูกค้าโอนช่วงเย็น',
};

const fallbacks = { lateFee: '50.00', depositAccountCode: '11-1101', paidDate: '2026-07-09' };

describe('apiMethodToWizard', () => {
  it('maps API methods back to wizard channels', () => {
    expect(apiMethodToWizard('CASH')).toBe('CASH');
    expect(apiMethodToWizard('BANK_TRANSFER')).toBe('TRANSFER');
    expect(apiMethodToWizard('QR_EWALLET')).toBe('QR');
    expect(apiMethodToWizard('CARD')).toBe('CARD');
  });

  it('falls back to CASH for unknown methods', () => {
    expect(apiMethodToWizard('ONLINE_GATEWAY')).toBe('CASH');
  });
});

describe('isAutoGeneratedRef', () => {
  it('detects the record-flow fallback <METHOD>-<timestamp> refs', () => {
    expect(isAutoGeneratedRef('CASH-1719999999999')).toBe(true);
    expect(isAutoGeneratedRef('BANK_TRANSFER-1719999999999')).toBe(true);
  });

  it('keeps genuine user references', () => {
    expect(isAutoGeneratedRef('KBANK-XYZ-001')).toBe(false);
    expect(isAutoGeneratedRef('INV-123')).toBe(false);
    expect(isAutoGeneratedRef(null)).toBe(false);
    expect(isAutoGeneratedRef('')).toBe(false);
  });
});

describe('draftToFormValues', () => {
  it('hydrates every editable field from the draft row', () => {
    const v = draftToFormValues(baseDraft, fallbacks);
    expect(v).toEqual({
      amount: '1515.83',
      method: 'TRANSFER',
      depositAccountCode: '11-1201',
      lateFee: '50.00',
      waiver: '25',
      waiverReasonCode: 'loyal_customer',
      waiverApproverId: 'u-approver',
      consumeAdvance: true,
      paidDate: '2026-07-09', // BKK-local date of the stored instant
      caseOverride: null,
      referenceNumber: 'KBANK-XYZ-001',
      slipUrl: 'https://s3/slips/abc.jpg',
      memo: 'ลูกค้าโอนช่วงเย็น',
    });
  });

  it('applies fallbacks for null account / lateFee / paidDate', () => {
    const v = draftToFormValues(
      { ...baseDraft, depositAccountCode: null, lateFee: null, paidDate: null },
      fallbacks,
    );
    expect(v.depositAccountCode).toBe('11-1101');
    expect(v.lateFee).toBe('50.00');
    expect(v.paidDate).toBe('2026-07-09');
  });

  it('filters the machine-generated transactionRef fallback', () => {
    const v = draftToFormValues({ ...baseDraft, transactionRef: 'CASH-1719999999999' }, fallbacks);
    expect(v.referenceNumber).toBe('');
  });

  it('maps PARTIAL / OVERPAY_ADVANCE cases to the override, others to null', () => {
    expect(draftToFormValues({ ...baseDraft, paymentCase: 'PARTIAL' }, fallbacks).caseOverride).toBe('PARTIAL');
    expect(
      draftToFormValues({ ...baseDraft, paymentCase: 'OVERPAY_ADVANCE' }, fallbacks).caseOverride,
    ).toBe('OVERPAY_ADVANCE');
    expect(draftToFormValues({ ...baseDraft, paymentCase: 'UNDERPAY' }, fallbacks).caseOverride).toBeNull();
  });

  it('drops stale waiver reason/approver when the waiver amount is zero', () => {
    const v = draftToFormValues(
      { ...baseDraft, lateFeeWaiverAmount: '0', lateFeeWaiverReasonCode: 'goodwill', waiverApproverId: 'u-x' },
      fallbacks,
    );
    expect(v.waiver).toBe('0');
    expect(v.waiverReasonCode).toBe('');
    expect(v.waiverApproverId).toBe('');
  });
});

describe('draftFingerprint (ลงบัญชี dirty-check)', () => {
  it('is stable across a hydrate → no-edit roundtrip', () => {
    const v = draftToFormValues(baseDraft, fallbacks);
    expect(draftFingerprint({ ...v })).toBe(draftFingerprint(v));
  });

  it('normalizes money formatting — "1515.8" and "1515.80" are the same value', () => {
    const v = draftToFormValues(baseDraft, fallbacks);
    expect(draftFingerprint({ ...v, amount: '1515.830' })).toBe(draftFingerprint(v));
  });

  it('ignores stale waiver reason/approver while the waiver is zero', () => {
    const v = { ...draftToFormValues(baseDraft, fallbacks), waiver: '0' };
    expect(draftFingerprint({ ...v, waiverReasonCode: 'goodwill' })).toBe(
      draftFingerprint({ ...v, waiverReasonCode: '' }),
    );
  });

  it('changes when the cashier edits a money field', () => {
    const v = draftToFormValues(baseDraft, fallbacks);
    expect(draftFingerprint({ ...v, amount: '1500.00' })).not.toBe(draftFingerprint(v));
    expect(draftFingerprint({ ...v, waiver: '30' })).not.toBe(draftFingerprint(v));
    expect(draftFingerprint({ ...v, lateFee: '75.79' })).not.toBe(draftFingerprint(v));
  });

  it('changes when method / account / date / case change', () => {
    const v = draftToFormValues(baseDraft, fallbacks);
    expect(draftFingerprint({ ...v, method: 'CASH' })).not.toBe(draftFingerprint(v));
    expect(draftFingerprint({ ...v, depositAccountCode: '11-1101' })).not.toBe(draftFingerprint(v));
    expect(draftFingerprint({ ...v, paidDate: '2026-07-08' })).not.toBe(draftFingerprint(v));
    expect(draftFingerprint({ ...v, caseOverride: 'PARTIAL' })).not.toBe(draftFingerprint(v));
  });

  it('trims free-text so trailing whitespace is not a dirty edit', () => {
    const v = draftToFormValues(baseDraft, fallbacks);
    expect(draftFingerprint({ ...v, memo: 'ลูกค้าโอนช่วงเย็น ' })).toBe(draftFingerprint(v));
  });
});
