/**
 * Thai user-facing microcopy. Centralizing makes tone consistent and
 * eases future i18n. Keys follow <page>.<element> naming.
 */

export const copy = {
  common: {
    loading: 'กำลังโหลด...',
    error: 'เกิดข้อผิดพลาด',
    retry: 'ลองใหม่',
    cancel: 'ยกเลิก',
    save: 'บันทึก',
    confirm: 'ยืนยัน',
    close: 'ปิด',
    next: 'ถัดไป',
    back: 'กลับ',
    viewAll: 'ดูทั้งหมด',
    contactLine: 'ทักไลน์',
  },

  home: {
    heroTitle: 'iPhone มือสองคุณภาพ\nผ่อนได้บัตร ปชช. ใบเดียว',
    heroDescription:
      'ร้านมือถือลพบุรี ของแท้ 100% รับประกันร้าน 30 วัน ตรวจสอบ 30 จุดก่อนส่งมอบ',
    featuredTitle: 'รุ่นยอดนิยม',
    whyUsTitle: 'ทำไมเลือก BESTCHOICE',
    testimonialsTitle: 'ลูกค้าพูดถึงเรา',
  },

  catalog: {
    pageTitle: 'สินค้าทั้งหมด',
    filterBrand: 'ยี่ห้อ',
    filterCondition: 'สภาพ',
    filterPrice: 'ราคา',
    sortPopular: 'ยอดนิยม',
    sortPriceAsc: 'ราคาต่ำ → สูง',
    sortPriceDesc: 'ราคาสูง → ต่ำ',
    emptyTitle: 'ไม่พบสินค้าตามตัวกรอง',
    emptyDescription: 'ลองเปลี่ยนยี่ห้อหรือช่วงราคา',
  },

  product: {
    reserveCta: 'จองเครื่องนี้ 15 นาที',
    specTitle: 'รายละเอียดสินค้า',
    conditionAFull: 'เกรด A — สภาพดีมาก เหมือนใหม่',
    conditionBFull: 'เกรด B — สภาพใช้งาน มีรอยเล็กน้อย',
    conditionCFull: 'เกรด C — สภาพมีรอย หรือตำหนิ',
  },

  cart: {
    pageTitle: 'ตะกร้าของคุณ',
    emptyTitle: 'ตะกร้าว่าง',
    emptyDescription: 'ลองเลือกสินค้าจากหน้ารุ่นยอดนิยม',
    emptyCta: 'ดูสินค้าทั้งหมด',
    proceedCta: 'ไปชำระเงิน',
    reservationExpireSoon: 'การจองจะหมดอายุในไม่ช้า',
    reservationExpired: 'การจองหมดอายุแล้ว — กรุณาจองใหม่',
  },

  checkout: {
    pageTitle: 'สั่งซื้อ',
    stepAddress: 'ที่อยู่',
    stepShipping: 'จัดส่ง',
    stepPayment: 'ชำระเงิน',
    placeOrderCta: 'ยืนยันสั่งซื้อ',
    summaryTitle: 'สรุปคำสั่งซื้อ',
    toggleSummary: 'ดูรายละเอียดยอดรวม',
    nextCta: 'ดำเนินการต่อ',
    backCta: 'ย้อนกลับ',
  },

  orderSuccess: {
    pageTitle: 'สั่งซื้อสำเร็จ',
    thankYou: 'ขอบคุณสำหรับการสั่งซื้อ',
    orderNumberLabel: 'เลขที่คำสั่งซื้อ',
    totalLabel: 'ยอดรวมทั้งสิ้น',
    paymentChannelLabel: 'ช่องทางชำระ',
    nextStepsTitle: 'ขั้นตอนถัดไป',
    nextStep1: 'ทางร้านตรวจสอบคำสั่งซื้อของคุณ',
    nextStep2: 'แพ็คสินค้าและจัดส่งภายใน 1 วันทำการ',
    nextStep3: 'รับสินค้าและรีวิวประสบการณ์ของคุณ',
    pendingPaymentNote: 'รอชำระเงิน...',
    paidNote: 'ทางร้านจะจัดส่งภายใน 1 วันทำการ',
    viewOrderCta: 'ดูคำสั่งซื้อ',
    continueShoppingCta: 'กลับไปซื้อเพิ่ม',
  },

  orders: {
    pageTitle: 'คำสั่งซื้อของฉัน',
    emptyTitle: 'ยังไม่มีคำสั่งซื้อ',
    emptyDescription: 'ลองดูสินค้าและสั่งซื้อดูครับ',
  },

  orderDetail: {
    breadcrumbList: 'คำสั่งซื้อของฉัน',
    productTitle: 'สินค้า',
    shippingAddressTitle: 'ที่อยู่จัดส่ง',
    paymentInfoTitle: 'ข้อมูลการชำระเงิน',
    paymentChannelLabel: 'ช่องทางชำระ',
    paidAtLabel: 'ชำระเมื่อ',
    trackingTitle: 'หมายเลขพัสดุ',
    cancelCta: 'ยกเลิก',
    refundCta: 'ขอคืนเงิน',
    confirmCancel: 'ยืนยันการยกเลิกคำสั่งซื้อ?',
    confirmRefund: 'ยืนยันขอคืนเงินสำหรับคำสั่งซื้อนี้?',
  },

  apply: {
    pageTitle: 'สมัครผ่อน',
    fullName: 'ชื่อ-นามสกุล',
    phone: 'เบอร์โทร',
    nationalId: 'เลขบัตรประชาชน',
    downPayment: 'จำนวนเงินดาวน์',
    totalMonths: 'จำนวนงวด (เดือน)',
    notes: 'หมายเหตุ (ถ้ามี)',
    submitCta: 'ส่งใบสมัคร',
    pdpaNotice:
      'ข้อมูลของคุณถูกเก็บภายใต้นโยบาย PDPA — ใช้เพื่อประเมินสินเชื่อเท่านั้น',
    successTitle: 'ส่งใบสมัครแล้ว',
    successDescription:
      'ทีมงานจะติดต่อกลับภายใน 2 ชั่วโมง (เวลาทำการ 09:00–20:00)',
  },

  tradeIn: {
    pageTitle: 'เก่าแลกใหม่',
    description: 'ตีราคามือถือเก่าสูงสุด ฿15,000 พร้อมซื้อเครื่องใหม่ในร้าน',
    submitCta: 'เริ่มทำเรื่อง',
    stepDevice: 'อุปกรณ์',
    stepCondition: 'สภาพ',
    stepPhotos: 'รูป',
    stepSeller: 'ผู้ขาย',
    sellerName: 'ชื่อ-นามสกุล',
    sellerPhone: 'เบอร์โทร (10 หลัก)',
    sellerLineId: 'LINE ID (ถ้ามี)',
    submitSuccess: 'ส่งเรื่องเก่าแลกใหม่แล้ว ทีมงานจะติดต่อกลับภายใน 24 ชั่วโมง',
    submitError: 'ส่งเรื่องไม่สำเร็จ กรุณาลองใหม่',
    photosRequired: 'รูปเครื่อง (อย่างน้อย 1 รูป)',
    statusTitle: 'สถานะการประเมิน',
    statusNotFound: 'ไม่พบข้อมูลเรื่องเก่าแลกใหม่',
    acceptPrice: 'ยอมรับราคา',
    rejectPrice: 'ปฏิเสธ',
    followUp: 'ทีมงานจะติดต่อกลับทาง LINE/โทรศัพท์ภายใน 24 ชั่วโมง',
  },

  buyback: {
    pageTitle: 'รับซื้อมือถือ',
    description: 'รับซื้อมือถือมือสองของแท้ พร้อมจ่ายเงินสดหรือโอนทันที',
    quoteCta: 'ตีราคาเบื้องต้น',
    submitCta: 'ส่งข้อมูล',
    stepDevice: 'อุปกรณ์',
    stepCondition: 'สภาพ',
    stepPhotos: 'รูป',
    stepSeller: 'ผู้ขาย',
    sellerName: 'ชื่อ-นามสกุล',
    sellerPhone: 'เบอร์โทร (10 หลัก)',
    sellerLineId: 'LINE ID (ถ้ามี)',
    submitSuccess: 'ส่งเรื่องรับซื้อแล้ว ทีมงานจะติดต่อกลับภายใน 24 ชั่วโมง',
    submitError: 'ส่งเรื่องไม่สำเร็จ กรุณาลองใหม่',
    quoteSuccess: 'รับราคาประเมินแล้ว',
    quoteError: 'ประเมินราคาไม่สำเร็จ',
    realPriceCta: 'ส่งรูปเพื่อราคาจริง',
    photosRequired: 'รูปเครื่อง (อย่างน้อย 1 รูป)',
    statusTitle: 'สถานะการรับซื้อ',
    statusNotFound: 'ไม่พบข้อมูลเรื่องรับซื้อ',
    acceptPrice: 'ยอมรับราคา',
    rejectPrice: 'ปฏิเสธ',
    followUp: 'ทีมงานจะติดต่อกลับทาง LINE/โทรศัพท์ภายใน 24 ชั่วโมง',
  },

  savingPlan: {
    pageTitle: 'ออมดาวน์',
    description: 'เก็บเงินดาวน์ทีละน้อย เริ่ม ฿500/เดือน',
    createCta: 'สร้างแผน',
  },

  review: {
    verifiedBadge: 'ซื้อจริง',
    writeCta: 'เขียนรีวิว',
    emptyTitle: 'ยังไม่มีรีวิว',
    emptyDescription: 'เป็นคนแรกที่รีวิวสินค้านี้',
  },

  howItWorks: {
    pageTitle: 'วิธีซื้อและผ่อน',
    intro:
      'ซื้อเครื่องกับ BESTCHOICE ง่ายใน 6 ขั้นตอน ใช้บัตรประชาชนใบเดียว ไม่ต้องใช้บัตรเครดิต',
    stepsTitle: '6 ขั้นตอนง่ายๆ',
    step1Title: 'เลือกเครื่อง',
    step1Description: 'เลือกรุ่นและสภาพที่ต้องการจากหน้ารายการสินค้า ดูรูปและรายละเอียดครบถ้วน',
    step2Title: 'จอง 15 นาที',
    step2Description: 'กดปุ่มจองเพื่อล็อคเครื่องไว้ 15 นาที กันเครื่องโดนคนอื่นซื้อก่อน',
    step3Title: 'กรอกใบสมัคร',
    step3Description: 'กรอกฟอร์มสั้นๆ ชื่อ-เบอร์-เลขบัตรประชาชน ข้อมูลปลอดภัยภายใต้ PDPA',
    step4Title: 'นัดหมายที่สาขา',
    step4Description: 'ทีมงานโทรกลับภายใน 2 ชั่วโมง เพื่อนัดวันและเวลามาที่ร้าน',
    step5Title: 'ชำระดาวน์',
    step5Description: 'มาที่ร้าน เซ็นสัญญา ชำระเงินดาวน์ ใช้เวลารวม 30 นาที',
    step6Title: 'รับเครื่อง + เริ่มผ่อน',
    step6Description: 'รับเครื่องกลับบ้านได้เลย เริ่มผ่อนตามงวดที่ตกลงไว้ผ่าน LINE',
    faqTitle: 'คำถามที่พบบ่อย',
    faq1Q: 'ไม่มีบัตรเครดิตผ่อนได้ไหม',
    faq1A: 'ผ่อนได้ครับ ใช้บัตรประชาชนใบเดียว ไม่ต้องใช้บัตรเครดิต และไม่ต้องมีผู้ค้ำ',
    faq2Q: 'ผ่อนได้กี่งวด',
    faq2A: 'เลือกได้ 3, 6, 9 หรือ 12 งวด แล้วแต่ความสะดวกของลูกค้า',
    faq3Q: 'ต้องดาวน์เท่าไร',
    faq3A: 'ดาวน์เริ่มต้นประมาณ 20-30% ของราคาเครื่อง ขึ้นกับรุ่นและจำนวนงวดที่เลือก',
    faq4Q: 'ถ้าผ่อนไม่ไหวทำอย่างไร',
    faq4A: 'ติดต่อทีมงานผ่าน LINE ทันที เรามีทางช่วยเช่น ยืดงวด ลดยอด หรือคืนเครื่อง',
    faq5Q: 'ซื้อเงินสดถูกกว่าไหม',
    faq5A: 'ราคาเครื่องเท่ากันทั้งเงินสดและผ่อน แต่ผ่อนจะมีค่าดอกเบี้ยบวกเพิ่ม',
  },

  shipping: {
    pageTitle: 'การจัดส่ง',
    intro1:
      'BESTCHOICE จัดส่งเครื่องทั่วประเทศไทยสำหรับการซื้อเงินสด และเปิดให้รับเครื่องที่สาขาลพบุรีสำหรับลูกค้าในพื้นที่',
    intro2: 'สำหรับลูกค้าผ่อน ต้องมารับเครื่องที่สาขาลพบุรีเท่านั้น เพื่อยืนยันเอกสารและเซ็นสัญญา',
    methodsTitle: 'ช่องทางจัดส่ง',
    branchPickupName: 'รับเครื่องที่สาขาลพบุรี',
    branchPickupFee: 'ฟรี',
    branchPickupEta: 'พร้อมรับทันที',
    branchPickupDescription: 'รับเครื่องที่ร้าน ตรวจเครื่องได้ละเอียดก่อนรับกลับบ้าน',
    kerryName: 'Kerry Express',
    kerryFee: '฿60',
    kerryEta: '1-2 วันทำการ',
    kerryDescription: 'ส่งทั่วประเทศ มีระบบเช็คสถานะพัสดุออนไลน์',
    flashName: 'Flash Express',
    flashFee: '฿50',
    flashEta: '1-2 วันทำการ',
    flashDescription: 'ส่งไวในราคาประหยัด เช็คสถานะผ่านแอปหรือเว็บได้',
    jtName: 'J&T Express',
    jtFee: '฿50',
    jtEta: '1-2 วันทำการ',
    jtDescription: 'ส่งทั่วประเทศ รับประกันพัสดุ มีระบบติดตาม',
    thailandPostName: 'ไปรษณีย์ไทย (EMS)',
    thailandPostFee: '฿70',
    thailandPostEta: '2-3 วันทำการ',
    thailandPostDescription: 'ส่งถึงทุกพื้นที่ แม้พื้นที่ห่างไกล',
    branchTitle: 'ที่ตั้งสาขาลพบุรี',
    branchAddress: 'เลขที่ 99/9 ถนนนารายณ์มหาราช ตำบลทะเลชุบศร อำเภอเมืองลพบุรี จังหวัดลพบุรี 15000',
    branchHours: 'เปิดทุกวัน 09:00 - 19:00 น.',
  },

  returns: {
    pageTitle: 'การคืน/เปลี่ยนสินค้า',
    intro:
      'BESTCHOICE ใส่ใจคุณภาพและความพอใจของลูกค้า หากพบปัญหาสามารถติดต่อทีมงานได้ทันทีผ่าน LINE',
    warrantyTitle: 'รับประกันร้าน 30 วัน',
    warrantyBody:
      'ทุกเครื่องรับประกันจากร้าน 30 วัน ครอบคลุมการใช้งานปกติ หากเครื่องมีปัญหาจากอุปกรณ์ภายใน ทางร้านจะซ่อมหรือเปลี่ยนเครื่องให้ฟรี',
    refundTitle: 'นโยบายคืนเงิน',
    refundBody:
      'คืนสินค้าภายใน 7 วัน หากเครื่องอยู่ในสภาพเดิม อุปกรณ์ครบ ไม่มีรอยเพิ่ม จะคืนเงินภายใน 3-5 วันทำการ ลูกค้าเป็นผู้ออกค่าจัดส่งคืน',
    contactTitle: 'วิธีติดต่อ',
    contactBody: 'แจ้งคืน/รับประกันผ่าน LINE หรือโทรเข้าสาขา ทีมงานพร้อมช่วยเหลือทุกวัน',
    lineCta: 'ทักไลน์ @bestchoice',
    phoneCta: 'โทร 036-XXX-XXX',
  },

  about: {
    pageTitle: 'เกี่ยวกับเรา',
    storyTitle: 'เรื่องราวของเรา',
    storyP1:
      'BESTCHOICE Phone Shop เริ่มต้นที่ลพบุรีในปี 2020 ด้วยความตั้งใจของเจ้าของร้านที่อยากให้คนในพื้นที่เข้าถึงมือถือคุณภาพได้ง่าย โดยไม่ต้องเดินทางไกลหรือใช้บัตรเครดิต',
    storyP2:
      'วันนี้เราดูแลลูกค้ามาแล้วกว่า 1,000 ราย ด้วยหลักการง่ายๆ ของแท้ โปร่งใส และดูแลใกล้ชิด เราเลือกเครื่องทุกเครื่องด้วยตัวเอง ตรวจ 30 จุด ก่อนส่งต่อให้ลูกค้า',
    timelineTitle: 'เส้นทางของเรา',
    milestone1Year: '2020',
    milestone1Title: 'ก่อตั้งร้าน',
    milestone1Description: 'เปิดสาขาแรกที่ลพบุรี เน้นขาย iPhone มือสองคุณภาพ',
    milestone2Year: '2022',
    milestone2Title: 'เริ่มบริการผ่อน',
    milestone2Description: 'เปิดผ่อนบัตรประชาชนใบเดียว ช่วยลูกค้าเข้าถึงได้ง่ายขึ้น',
    milestone3Year: '2024',
    milestone3Title: 'ลูกค้าครบ 1,000 ราย',
    milestone3Description: 'รีวิว 4.9 ดาวจากลูกค้าจริงกว่า 500 รีวิว',
    milestone4Year: '2026',
    milestone4Title: 'เปิดระบบออนไลน์',
    milestone4Description: 'เว็บไซต์ใหม่ สั่งซื้อและสมัครผ่อนได้ตลอด 24 ชม.',
    valuesTitle: 'คุณค่าของเรา',
    value1Title: 'ของแท้ 100%',
    value1Description: 'ทุกเครื่องตรวจสอบจริง แกะกล่อง ซีเรียลตรงกับตัวเครื่อง',
    value2Title: 'รับประกัน 30 วัน',
    value2Description: 'หลังซื้อไปแล้วมีปัญหา ติดต่อเราได้ทันทีในช่วงประกัน',
    value3Title: 'บริการในพื้นที่',
    value3Description: 'สาขาลพบุรีพร้อมรับเรื่องลูกค้าในพื้นที่ใกล้เคียง ไม่ต้องเดินทางไกล',
  },

  contact: {
    pageTitle: 'ติดต่อเรา',
    intro: 'ทีมงาน BESTCHOICE ยินดีให้คำปรึกษา ตอบข้อสงสัยเรื่องเครื่อง การผ่อน และบริการต่างๆ',
    lineTitle: 'LINE Official',
    lineHandle: '@bestchoice',
    lineCta: 'เปิดแชท',
    lineDescription: 'ตอบไวในเวลาทำการ ส่งรูป/คลิปให้ดูเครื่องได้',
    phoneTitle: 'โทรศัพท์',
    phoneNumber: '036-XXX-XXX',
    phoneCta: 'โทร',
    phoneDescription: 'รับสายทุกวัน 09:00 - 19:00 น.',
    formTitle: 'ฝากข้อความ',
    formDescription: 'กรอกข้อมูลและข้อความ ทีมงานจะติดต่อกลับโดยเร็วที่สุด',
    formNameLabel: 'ชื่อ-นามสกุล',
    formNamePlaceholder: 'กรอกชื่อของคุณ',
    formPhoneLabel: 'เบอร์โทร',
    formPhonePlaceholder: '08X-XXX-XXXX',
    formMessageLabel: 'ข้อความ',
    formMessagePlaceholder: 'สอบถามรุ่นเครื่อง ราคา หรือขอคำปรึกษา',
    formSubmitCta: 'ส่งข้อความ',
    addressTitle: 'ที่อยู่และเวลาทำการ',
    address: 'เลขที่ 99/9 ถนนนารายณ์มหาราช ตำบลทะเลชุบศร อำเภอเมืองลพบุรี จังหวัดลพบุรี 15000',
    hours: 'เปิดทุกวัน 09:00 - 19:00 น.',
  },
} as const;
