import { createHash } from 'crypto';
import { join } from 'path';
import * as forge from 'node-forge';
import request from 'supertest';
import { Prisma } from '@prisma/client';
import { DOCUMENT_STYLE } from '@installment/shared';
import { bodyBuffer, DocumentsHarness, Session, startDocumentsApp } from './support/harness';
import { DocumentsWorld, seedDocumentsWorld } from './support/fixtures';
import { activateContract } from './support/receipts-fixtures';
import { attachBranchToCompany, bangkokYearMonth, createLongAddressCustomer, createVatContract, installSyntheticRd, SYNTHETIC_RD_CONFIG, synthesizeCertificate, SyntheticCertificate, SyntheticRd, thaiInvoiceDate, VatContract } from './support/e-tax-fixtures';
import { domainDir, recordScenario, saveArtifact, ScenarioRecord, sha256 } from './support/artifacts';
import { foldThai, isA4, pageContaining, pageText, parsePdf, ParsedPdf, sizesOfText, textSizes } from './support/pdf';

/**
 * DOC-07 (issue #1566): the e-Tax document center end to end — payments booked
 * through the real receipt route become the invoice source, the XML lifecycle
 * runs through the real service with a synthetic Revenue Department behind a
 * jest spy, the PDF is fetched from the authenticated route and checked against
 * the persisted rows, and nothing about a download signs, submits or mutates.
 */
const DOMAIN = 'e-tax';
const GUARDS = ['CsrfGuard', 'ThrottlerGuard', 'JwtAuthGuard→JwtStrategy(DB user)', 'JwtAudienceGuard', 'RolesGuard (@Roles OWNER/FINANCE_MANAGER/ACCOUNTANT; generate FM+, sign/submit/retry/config OWNER)', 'ETaxService company→branch scoping', 'EntityScopeInterceptor', 'AuditInterceptor'];
const SIMULATED = [
  'Revenue Department web service = jest spy on RdApiClient.prototype (submit / checkStatus / ping): no request leaves the process; verdicts are scripted per scenario',
  'PKCS#7 signature made with a self-signed certificate generated by openssl for this run (not an RD-approved CA) — proves the signing path, not RD acceptance',
  'ETaxAutoSubmitCron disabled for the run so the hourly job cannot move statuses mid-scenario',
  'LINE/SMS/e-mail transports recorded, never sent; private local storage',
  'synthetic company/branches/customers/contracts; payments booked through POST /payments/record',
];
const scenario = (record: Omit<ScenarioRecord, 'documents' | 'guards' | 'renderer' | 'source' | 'status' | 'simulated'> & Partial<ScenarioRecord>): ScenarioRecord => ({
  documents: ['TAX_INVOICE'], guards: GUARDS, renderer: 'jspdf', source: 'api', status: 'PASS', simulated: SIMULATED, ...record,
});

interface PaymentRow { id: string; installmentNo: number; contractId: string; amountPaid: string; vatAmount: string; base: string; paidDate: Date; status: string }
interface SubmissionRow { id: string; paymentId: string; status: string; invoiceNumber: string | null; xmlContent: string; signedXml: string | null; rdSubmissionId: string | null; rejectReason: string | null; retryCount: number; updatedAt: Date; acceptedAt: Date | null }

const money = (value: string | number | Prisma.Decimal) => new Prisma.Decimal(value.toString()).toFixed(2);
const isoBangkok = (date: Date) => date.toLocaleDateString('sv-SE', { timeZone: 'Asia/Bangkok' });

describe('DOC-07 e-Tax invoices — real payment source, XML lifecycle against a synthetic RD, authenticated PDF', () => {
  let h: DocumentsHarness;
  let world: DocumentsWorld;
  let owner: Session;
  let financeManager: Session;
  let accountant: Session;
  let branchManagerA: Session;
  let salesA: Session;
  let financeCompanyId: string;
  let shopCompanyId: string;
  let contractA: VatContract;
  let contractLong: VatContract;
  let contractB: VatContract;
  let longCustomer: { id: string; name: string; nationalId: string; address: string };
  let cert: SyntheticCertificate;
  const paid: Record<'A1' | 'A2' | 'L1' | 'B1', PaymentRow> = {} as never;
  let rd: SyntheticRd;
  let outboundAfterBookings = 0;
  const { year, month } = bangkokYearMonth();
  const subs: { accepted?: SubmissionRow; pending?: SubmissionRow; rejected?: SubmissionRow } = {};

  const ok = async (test: request.Test, status = 200, label = 'request'): Promise<request.Response> => {
    const response = await test;
    if (response.status !== status) throw new Error(`${label} → ${response.status} (expected ${status}) ${JSON.stringify(response.body).slice(0, 400)}`);
    return response;
  };
  const c = (session: Session | null, company: 'SHOP' | 'FINANCE' | null = 'FINANCE') => h.client({ session, company });
  const loadPayment = async (id: string): Promise<PaymentRow> => {
    const row = await h.prisma.payment.findUniqueOrThrow({ where: { id }, select: { id: true, installmentNo: true, contractId: true, amountPaid: true, vatAmount: true, paidDate: true, status: true } });
    const vat = row.vatAmount ?? new Prisma.Decimal(0);
    return { id: row.id, installmentNo: row.installmentNo, contractId: row.contractId, amountPaid: money(row.amountPaid), vatAmount: money(vat), base: money(row.amountPaid.minus(vat)), paidDate: row.paidDate as Date, status: row.status };
  };
  const loadSubmission = async (id: string): Promise<SubmissionRow> => {
    const row = await h.prisma.eTaxSubmission.findUniqueOrThrow({ where: { id } });
    return { id: row.id, paymentId: row.paymentId, status: row.status, invoiceNumber: row.invoiceNumber, xmlContent: row.xmlContent, signedXml: row.signedXml, rdSubmissionId: row.rdSubmissionId, rejectReason: row.rejectReason, retryCount: row.retryCount, updatedAt: row.updatedAt, acceptedAt: row.acceptedAt };
  };
  const auditActions = async (entityId: string) => (await h.prisma.auditLog.findMany({ where: { entity: 'etax_submission', entityId }, orderBy: { createdAt: 'asc' }, select: { action: true, userId: true } })).map((r) => r.action);
  // POST /payments/record: the global ThrottlerGuard and the route's UserThrottlerGuard share one limit
  // (DOC-01 observation) — keep at most two bookings per 11 s and rotate real users with branch access.
  const recordTimes: number[] = [];
  let referenceSeq = 0;
  const pay = async (session: Session, contract: VatContract, installmentNo: number) => {
    const window = recordTimes.filter((at) => Date.now() - at < 11_000);
    if (window.length >= 2) await new Promise((resolve) => setTimeout(resolve, 11_000 - (Date.now() - window[0]) + 250));
    recordTimes.push(Date.now());
    const amount = Number(contract.installments[installmentNo - 1].amountDue);
    await ok(h.client({ session }).post('/payments/record', { contractId: contract.id, installmentNo, amount, paymentMethod: 'CASH', depositAccountCode: '11-1101', case: 'NORMAL', transactionRef: `${world.prefix}-ET-REF-${++referenceSeq}` }), 201, `POST /payments/record ${contract.contractNumber}#${installmentNo}`);
    return loadPayment(contract.installments[installmentNo - 1].paymentId);
  };
  const has = (pdf: ParsedPdf, needle: string) => foldThai(pdf.pages.map(pageText).join('\n')).includes(foldThai(needle));
  const expectAll = (pdf: ParsedPdf, needles: string[]) => { for (const needle of needles) expect({ needle, found: has(pdf, needle) }).toEqual({ needle, found: true }); };
  const pdfSummary = (pdf: ParsedPdf) => ({ pageCount: pdf.pageCount, fonts: pdf.fonts, sizes: textSizes(pdf).slice(0, 6), pages: pdf.pages.map((p) => ({ w: p.widthPt.toFixed(2), h: p.heightPt.toFixed(2), lines: p.lines })) });
  const invoicePdf = async (session: Session | null, paymentId: string, status = 200) => {
    const response = await c(session).get(`/e-tax/invoices/${paymentId}/pdf`);
    if (response.status !== status) throw new Error(`GET /e-tax/invoices/${paymentId}/pdf → ${response.status} (expected ${status}) ${JSON.stringify(response.body).slice(0, 300)}`);
    return response;
  };
  const xmlAmount = (xml: string, tag: string) => { const m = new RegExp(`<${tag}[^>]*>([^<]+)</${tag}>`).exec(xml); return m ? money(m[1]) : null; };

  beforeAll(async () => {
    h = await startDocumentsApp();
    world = await seedDocumentsWorld(h.prisma);
    [owner, financeManager, accountant, branchManagerA, salesA] = await Promise.all(
      [world.users.owner, world.users.financeManager, world.users.accountant, world.users.branchManagerA, world.users.salesA].map((u) => h.login(u.email, u.password)),
    );
    // The document center scopes by company → branches: branch A is FINANCE's, branch B is SHOP's.
    financeCompanyId = await attachBranchToCompany(h.prisma, world.branches.a.id, 'FINANCE');
    shopCompanyId = await attachBranchToCompany(h.prisma, world.branches.b.id, 'SHOP');
    longCustomer = await createLongAddressCustomer(h.prisma, world.prefix);
    const make = async (label: string, branchId: string, customerId: string, salespersonId: string) => {
      const contract = await createVatContract(h.prisma, { prefix: world.prefix, label, branchId, customerId, salespersonId });
      await activateContract(h.app, contract.id);
      return contract;
    };
    contractA = await make('A', world.branches.a.id, world.customer.id, world.users.salesA.id);
    contractLong = await make('L', world.branches.a.id, longCustomer.id, world.users.salesA.id);
    contractB = await make('B', world.branches.b.id, world.customer.id, world.users.salesB.id);
    paid.A1 = await pay(salesA, contractA, 1);
    paid.A2 = await pay(branchManagerA, contractA, 2);
    paid.L1 = await pay(owner, contractLong, 1);
    paid.B1 = await pay(financeManager, contractB, 1);
    // Booking a receipt pushes the customer a LINE receipt — recorded by the harness, never sent.
    outboundAfterBookings = h.external.calls.length;
    // Synthetic RD + certificate; the hourly auto-submit job is muted for the run.
    rd = installSyntheticRd();
    cert = synthesizeCertificate(join(domainDir(DOMAIN), 'synthetic-cert'));
    // The e-Tax config is global (IntegrationConfig, not world-scoped): a full run shares one
    // database across suites, so start from the documented default whatever ran before.
    await ok(c(owner).put('/integrations/e-tax/config', { submitMode: 'disabled' }), 200, 'e-tax config reset');
  }, 300000);

  afterAll(async () => {
    if (h && owner) await c(owner).put('/integrations/e-tax/config', { submitMode: 'disabled' }).catch(() => undefined);
    rd?.restore();
    await h?.close();
  });

  it('lists PAID installments with VAT for the selected company and month, scoped by role; the page-size the web asks for is checked', async () => {
    // ResponseInterceptor envelope: body.data = { data: rows, total, page, limit }
    const list = async (session: Session | null, companyId: string, status = 200) => ok(c(session).get('/e-tax/invoices').query({ companyId, year, month, limit: 200 }), status, `GET /e-tax/invoices ${companyId}`);
    // In a full `docs:check` run every domain shares one disposable database, so other worlds
    // (e.g. the browser scenario) may have attached their own branches to the same legal entity —
    // assert on this world's contracts only.
    const rowsOf = (response: request.Response) => (response.body.data as { data: Array<Record<string, unknown>> }).data.filter((row) => String(row.contractNumber).includes(world.prefix));
    const finance = rowsOf(await list(owner, financeCompanyId));
    const byPayment = new Map(finance.map((row) => [row.paymentId as string, row]));
    expect([...byPayment.keys()].sort()).toEqual([paid.A1.id, paid.A2.id, paid.L1.id].sort());
    for (const row of [paid.A1, paid.A2, paid.L1]) {
      const listed = byPayment.get(row.id)!;
      expect({ base: money(listed.amountBeforeVat as string), vat: money(listed.vatAmount as string), total: money(listed.total as string), installmentNo: listed.installmentNo, contractNumber: listed.contractNumber, customerName: listed.customerName, customerTaxId: listed.customerTaxId })
        .toEqual({ base: row.base, vat: row.vatAmount, total: row.amountPaid, installmentNo: row.installmentNo, contractNumber: row.contractId === contractA.id ? contractA.contractNumber : contractLong.contractNumber, customerName: row.contractId === contractA.id ? world.customer.name : longCustomer.name, customerTaxId: row.contractId === contractA.id ? (await h.prisma.customer.findUniqueOrThrow({ where: { id: world.customer.id } })).nationalId : longCustomer.nationalId });
    }
    expect(Number(paid.A1.vatAmount)).toBeGreaterThan(0);
    const shop = rowsOf(await list(owner, shopCompanyId));
    expect(shop.map((r) => r.paymentId)).toEqual([paid.B1.id]);
    // Unpaid installment 3 of contract A is not a source.
    expect(finance.some((row) => row.paymentId === contractA.installments[2].paymentId)).toBe(false);
    expect(rowsOf(await list(financeManager, financeCompanyId)).length).toBe(3);
    expect(rowsOf(await list(accountant, financeCompanyId)).length).toBe(3);
    await list(branchManagerA, financeCompanyId, 403);
    await list(salesA, financeCompanyId, 403);
    await list(null, financeCompanyId, 401);
    await ok(c(owner).get('/e-tax/invoices').query({ year, month }), 400, 'missing companyId');
    await ok(c(owner).get('/e-tax/invoices').query({ companyId: financeCompanyId, year, month: 13 }), 400, 'month 13');
    const csv = await ok(c(owner).get('/e-tax/export-csv').query({ companyId: financeCompanyId, year, month }), 200, 'export-csv');
    expect(csv.headers['content-type']).toMatch(/text\/csv/);
    expect(csv.headers['content-disposition']).toContain(`e-tax-${year}-${String(month).padStart(2, '0')}.csv`);
    const csvText = bodyBuffer(csv).toString('utf8');
    expect(csvText).toContain(contractA.contractNumber);
    expect(csvText).toContain(paid.A1.vatAmount);
    // The document center page requests every submission with ?limit=500 to map statuses onto the list.
    const webPageSize = await c(owner).get('/e-tax-xml').query({ limit: 500 });
    const artifacts = [
      saveArtifact(DOMAIN, 'invoice-list.json', JSON.stringify({ year, month, financeCompanyId, shopCompanyId, finance, shop, payments: paid, submissionsLimit500: { status: webPageSize.status, body: webPageSize.body } }, null, 2)).relativePath,
      saveArtifact(DOMAIN, `e-tax-${year}-${String(month).padStart(2, '0')}.csv`, csvText).relativePath,
    ];
    recordScenario(DOMAIN, scenario({ id: `${DOMAIN}/invoice-source`, title: 'GET /e-tax/invoices: 3 PAID VAT installments under FINANCE (branch A), 1 under SHOP (branch B), unpaid excluded; amounts = Payment.amountPaid / vatAmount; OWNER/FM/ACCOUNTANT 200, BM/SALES 403, no token 401, bad params 400; CSV export matches', documents: ['TAX_INVOICE_LIST', 'E_TAX_CSV'], routes: ['POST /api/payments/record', 'GET /api/e-tax/invoices', 'GET /api/e-tax/export-csv', 'GET /api/e-tax-xml'], renderer: 'none', artifacts, notes: `GET /e-tax-xml?limit=500 (exactly what ETaxPage sends) answered ${webPageSize.status}${webPageSize.status !== 200 ? ` — ${JSON.stringify(webPageSize.body).slice(0, 160)}` : ''}. Payment.vatAmount is written by the schedule generator at contract creation (not at receipt time); the fixture uses the same generatePaymentSchedule call as ContractQuoteService` }));
  });

  it('XML lifecycle through the real service: generate (PENDING, sequential ET number) → sign with the synthetic certificate → submit → poll → ACCEPTED; a second document is REJECTED by the synthetic RD', async () => {
    const generate = async (session: Session, paymentId: string, status = 201) => ok(c(session).post(`/e-tax-xml/generate/${paymentId}`), status, `generate ${paymentId}`);
    const created = (await generate(financeManager, paid.A1.id)).body.data as { id: string };
    let sub = await loadSubmission(created.id);
    expect(sub.status).toBe('PENDING');
    // Sequential per Bangkok day across the whole database (other worlds in a full run may already hold numbers).
    const seq = (invoiceNumber: string | null) => Number(String(invoiceNumber).split('-')[2]);
    expect(sub.invoiceNumber).toMatch(new RegExp(`^ET-${isoBangkok(paid.A1.paidDate).replace(/-/g, '')}-\\d{4}$`));
    expect(seq(sub.invoiceNumber)).toBeGreaterThanOrEqual(1);
    expect(sub.xmlContent).toContain(`<cbc:ID>${sub.invoiceNumber}</cbc:ID>`);
    expect(sub.xmlContent).toContain(`<cbc:IssueDate>${isoBangkok(paid.A1.paidDate)}</cbc:IssueDate>`);
    const finance = await h.prisma.companyInfo.findFirstOrThrow({ where: { companyCode: 'FINANCE' } });
    // ETDA TXID scheme = taxId-branchCode (HQ 00000); the buyer's 13-digit id gets the same suffix.
    expect(sub.xmlContent).toContain(`<cbc:CompanyID schemeID="TXID">${finance.taxId}-${finance.taxBranchCode ?? '00000'}</cbc:CompanyID>`);
    expect(sub.xmlContent).toContain(`<cbc:Name>${finance.nameTh}</cbc:Name>`);
    const customer = await h.prisma.customer.findUniqueOrThrow({ where: { id: world.customer.id } });
    expect(sub.xmlContent).toContain(`<cbc:CompanyID schemeID="TXID">${customer.nationalId}-00000</cbc:CompanyID>`);
    expect(sub.xmlContent).toContain(`<cbc:Name>${customer.name}</cbc:Name>`);
    expect(sub.xmlContent).toContain(`<cbc:StreetName>${customer.addressIdCard}</cbc:StreetName>`);
    expect({ taxInclusive: xmlAmount(sub.xmlContent, 'cbc:TaxInclusiveAmount'), payable: xmlAmount(sub.xmlContent, 'cbc:PayableAmount'), taxExclusive: xmlAmount(sub.xmlContent, 'cbc:TaxExclusiveAmount'), lineExtension: xmlAmount(sub.xmlContent, 'cbc:LineExtensionAmount') })
      .toEqual({ taxInclusive: paid.A1.amountPaid, payable: paid.A1.amountPaid, taxExclusive: paid.A1.base, lineExtension: paid.A1.base });
    expect(xmlAmount(sub.xmlContent, 'cbc:TaxAmount')).toBe(paid.A1.vatAmount);
    expect(sub.xmlContent).toContain(`${contractA.contractNumber}/1`);
    // Idempotent: a second generate returns the same document and number.
    expect(((await generate(financeManager, paid.A1.id)).body.data as { id: string; invoiceNumber: string })).toMatchObject({ id: sub.id, invoiceNumber: sub.invoiceNumber });
    await generate(accountant, paid.A2.id, 403);

    // Gate: signing needs submitMode=enabled + certificate; OWNER only.
    await ok(c(financeManager).post(`/e-tax-xml/${sub.id}/sign`), 403, 'FM sign');
    const closed = await ok(c(owner).post(`/e-tax-xml/${sub.id}/sign`), 400, 'sign while disabled');
    expect(String(closed.body.message)).toContain('e-Tax ปิดอยู่');
    await ok(c(accountant).put('/integrations/e-tax/config', { submitMode: 'enabled' }), 403, 'ACCOUNTANT config');
    await ok(c(owner).put('/integrations/e-tax/config', { submitMode: 'enabled', certPath: cert.certPath, certPassword: cert.password, ...SYNTHETIC_RD_CONFIG }), 200, 'OWNER config');
    const checkConfig = (await ok(c(owner).post('/e-tax-xml/check-config'), 201, 'check-config')).body.data as { submitMode: string; certConfigured: boolean; rdReachable: boolean; rdDetail: string };
    expect(checkConfig).toMatchObject({ submitMode: 'enabled', certConfigured: true, rdReachable: true });
    expect((await ok(c(accountant).get('/e-tax-xml/submit-mode'), 200, 'submit-mode')).body.data).toEqual({ mode: 'sandbox' });

    await ok(c(owner).post(`/e-tax-xml/${sub.id}/sign`), 201, 'OWNER sign');
    sub = await loadSubmission(sub.id);
    expect(sub.status).toBe('SIGNED');
    const signature = /<ds:SignatureValue>([^<]+)<\/ds:SignatureValue>/.exec(sub.signedXml ?? '');
    expect(signature).not.toBeNull();
    // Independent check of the CMS bundle: DER parses, the signer certificate is the synthetic one, content is detached.
    const cms = forge.pkcs7.messageFromAsn1(forge.asn1.fromDer(forge.util.decode64(signature![1]))) as unknown as { certificates: forge.pki.Certificate[]; signers?: unknown[] };
    expect(cms.certificates[0].subject.getField('CN').value).toBe(cert.commonName);
    expect(sub.signedXml).toContain(`<cbc:ID>${sub.invoiceNumber}</cbc:ID>`);

    await ok(c(financeManager).post(`/e-tax-xml/${sub.id}/submit`), 403, 'FM submit');
    rd.submitVerdict = 'ACCEPT';
    await ok(c(owner).post(`/e-tax-xml/${sub.id}/submit`), 201, 'OWNER submit');
    sub = await loadSubmission(sub.id);
    expect(sub.status).toBe('SUBMITTED');
    expect(sub.rdSubmissionId).toMatch(/^RD-SYNTHETIC-/);
    const submitCall = rd.calls.find((call) => call.op === 'submit');
    expect(submitCall).toMatchObject({ endpoint: SYNTHETIC_RD_CONFIG.rdEndpoint, username: SYNTHETIC_RD_CONFIG.rdUsername, signedXmlSha256: sha256(sub.signedXml as string) });
    rd.pollStatus = 'PENDING';
    await ok(c(financeManager).post(`/e-tax-xml/${sub.id}/poll`), 201, 'poll pending');
    expect((await loadSubmission(sub.id)).status).toBe('SUBMITTED');
    rd.pollStatus = 'ACCEPTED';
    await ok(c(financeManager).post(`/e-tax-xml/${sub.id}/poll`), 201, 'poll accepted');
    sub = await loadSubmission(sub.id);
    expect(sub.status).toBe('ACCEPTED');
    expect(sub.acceptedAt).not.toBeNull();
    expect(await auditActions(sub.id)).toEqual(['ETAX_XML_GENERATED', 'ETAX_SIGNED', 'ETAX_SUBMITTED', 'ETAX_ACCEPTED']);
    subs.accepted = sub;

    // Second document: PENDING only (never signed).
    subs.pending = await loadSubmission(((await generate(owner, paid.A2.id)).body.data as { id: string }).id);
    expect(seq(subs.pending.invoiceNumber)).toBe(seq(sub.invoiceNumber) + 1);
    // Third document: signed and rejected by the synthetic RD.
    const rejected = await loadSubmission(((await generate(owner, paid.L1.id)).body.data as { id: string }).id);
    expect(seq(rejected.invoiceNumber)).toBe(seq(sub.invoiceNumber) + 2);
    await ok(c(owner).post(`/e-tax-xml/${rejected.id}/sign`), 201, 'sign L1');
    rd.submitVerdict = 'REJECT';
    await ok(c(owner).post(`/e-tax-xml/${rejected.id}/submit`), 201, 'submit L1');
    subs.rejected = await loadSubmission(rejected.id);
    expect(subs.rejected).toMatchObject({ status: 'REJECTED', rejectReason: 'SYNTHETIC RD: schema rejected (test verdict)' });
    expect(await auditActions(rejected.id)).toEqual(['ETAX_XML_GENERATED', 'ETAX_SIGNED', 'ETAX_REJECTED']);
    // Retry is a separate OWNER action (back to SIGNED); the page's "สร้าง XML ใหม่" button calls generate, which is idempotent.
    expect(((await generate(owner, paid.L1.id)).body.data as { id: string; status: string })).toMatchObject({ id: rejected.id, status: 'REJECTED' });
    const found = (await ok(c(accountant).get(`/e-tax-xml/${sub.id}`), 200, 'findOne')).body.data as { status: string; payment: { contract: { contractNumber: string } } };
    expect(found).toMatchObject({ status: 'ACCEPTED', payment: { contract: { contractNumber: contractA.contractNumber } } });
    rd.submitVerdict = 'ACCEPT';
    // Regression (defect found in this issue): XML generation for an UNPAID installment (row 3 of contract A,
    // vatAmount 99.17, amountPaid 0) used to answer 201 and consume ET-…-0004 for an XML with a negative
    // taxable amount. It must refuse and allocate nothing.
    const unpaidProbe = await c(owner).post(`/e-tax-xml/generate/${contractA.installments[2].paymentId}`);
    const unpaidSubmission = await h.prisma.eTaxSubmission.findFirst({ where: { paymentId: contractA.installments[2].paymentId } });
    expect(unpaidProbe.status).toBe(400);
    expect(String(unpaidProbe.body.message)).toContain('ยังไม่ได้ชำระ');
    expect(unpaidSubmission).toBeNull();
    expect(await h.prisma.eTaxSubmission.count({ where: { payment: { contractId: { in: [contractA.id, contractLong.id, contractB.id] } } } })).toBe(3);

    const artifacts = [
      saveArtifact(DOMAIN, `${sub.invoiceNumber}.xml`, sub.xmlContent).relativePath,
      saveArtifact(DOMAIN, `${sub.invoiceNumber}.signed.xml`, sub.signedXml as string).relativePath,
      saveArtifact(DOMAIN, 'rd-calls.json', JSON.stringify(rd.calls, null, 2)).relativePath,
      saveArtifact(DOMAIN, 'submissions.json', JSON.stringify({ accepted: { ...subs.accepted, xmlContent: undefined, signedXml: undefined }, pending: { ...subs.pending, xmlContent: undefined }, rejected: { ...subs.rejected, xmlContent: undefined, signedXml: undefined }, checkConfig, certificate: { subject: cert.subject, path: cert.certPath }, unpaidProbe: { status: unpaidProbe.status, body: unpaidProbe.body, submission: unpaidSubmission ? { id: unpaidSubmission.id, status: unpaidSubmission.status, invoiceNumber: unpaidSubmission.invoiceNumber } : null } }, null, 2)).relativePath,
    ];
    recordScenario(DOMAIN, scenario({ id: `${DOMAIN}/xml-lifecycle`, title: 'generate → sign (self-signed PKCS#7, CMS verified) → submit → poll → ACCEPTED through the real ETaxXmlService with a synthetic RD; second document PENDING, third REJECTED; gates: FM cannot sign/submit, signing refused while submitMode=disabled, ACCOUNTANT cannot change config', documents: ['E_TAX_XML'], routes: ['POST /api/e-tax-xml/generate/:paymentId', 'POST /api/e-tax-xml/:id/sign', 'POST /api/e-tax-xml/:id/submit', 'POST /api/e-tax-xml/:id/poll', 'GET /api/e-tax-xml/:id', 'PUT /api/integrations/e-tax/config', 'POST /api/e-tax-xml/check-config', 'GET /api/e-tax-xml/submit-mode'], renderer: 'none', artifacts, unverified: ['acceptance by the real Revenue Department (sandbox or production) — verdicts here are scripted'], notes: `Observation: the document center's "สร้าง XML ใหม่" button on a REJECTED/ERROR row calls POST generate, which returns the existing submission unchanged (retry needs POST :id/retry, which the page never calls). Observation: submit-mode reports "sandbox" for any non-etax_v2 endpoint, including a synthetic one. Defect fixed in this issue: POST generate for an UNPAID installment answered 201 and consumed a sequential ET number for an XML with TaxableAmount -99.17 / PayableAmount 0.00 (ETaxXmlService.loadPaymentForXml did not check Payment.status); now ${unpaidProbe.status} "${String(unpaidProbe.body.message)}" and nothing is created` }));
  });

  it('authenticated PDF: the tax invoice matches the persisted payment, buyer and FINANCE issuer; the download signs nothing, submits nothing and changes no status', async () => {
    const row = paid.A1;
    const before = { submission: await loadSubmission(subs.accepted!.id), payment: await loadPayment(row.id), rdCalls: rd.calls.length, audits: await auditActions(subs.accepted!.id) };
    const response = await invoicePdf(owner, row.id);
    expect(response.headers['content-type']).toMatch(/application\/pdf/);
    expect(response.headers['content-disposition']).toBe(`inline; filename="receipt-${row.id}.pdf"`);
    const bytes = bodyBuffer(response);
    const pdf = await parsePdf(bytes);
    const finance = await h.prisma.companyInfo.findFirstOrThrow({ where: { companyCode: 'FINANCE' } });
    const customer = await h.prisma.customer.findUniqueOrThrow({ where: { id: world.customer.id } });
    expect(pdf.pageCount).toBe(1);
    expect(pdf.pages.every(isA4)).toBe(true);
    expect(pdf.fonts.length).toBeGreaterThan(0);
    expect(pdf.fonts.every((font) => font.startsWith(DOCUMENT_STYLE.pdfFontFamily))).toBe(true);
    expect(textSizes(pdf)[0].size).toBe(DOCUMENT_STYLE.bodyPt);
    // Title line "BESTCHOICE … ใบกำกับภาษี" at 18 pt (the words ใบกำกับภาษี also occur in 16 pt party labels and the 12 pt disclaimer).
    expect(sizesOfText(pdf, 'BESTCHOICE')).toEqual([DOCUMENT_STYLE.headingPt]);
    expect(sizesOfText(pdf, 'ใบกำกับภาษี')).toContain(DOCUMENT_STYLE.headingPt);
    expect(sizesOfText(pdf, 'TAX INVOICE')).toEqual([DOCUMENT_STYLE.footerPt]);
    expect(sizesOfText(pdf, 'รวมทั้งสิ้น')).toEqual([DOCUMENT_STYLE.bodyPt]);
    const pdfNumber = `TX-${row.id.slice(0, 8).toUpperCase()}`;
    expectAll(pdf, ['ใบกำกับภาษี', 'TAX INVOICE', 'ต้นฉบับ / ORIGINAL', `เลขที่ ${pdfNumber}`, `วันที่ ${thaiInvoiceDate(row.paidDate)}`,
      'ผู้ออกใบกำกับภาษี (ผู้ขาย)', finance.nameTh, `เลขประจำตัวผู้เสียภาษี: ${finance.taxId}`, `ที่อยู่: ${finance.address}`, `โทร: ${finance.phone}`,
      'ผู้ซื้อ / ผู้รับบริการ', customer.name, `เลขประจำตัวผู้เสียภาษี: ${customer.nationalId}`, `ที่อยู่: ${customer.addressIdCard}`,
      `อ้างอิงสัญญา: ${contractA.contractNumber}`, 'งวดที่: 1', `ค่างวดผ่อนชำระตามสัญญา ${contractA.contractNumber} งวดที่ 1`,
      'ราคาก่อนภาษีมูลค่าเพิ่ม', row.base, 'ภาษีมูลค่าเพิ่ม 7%', row.vatAmount, 'รวมทั้งสิ้น', row.amountPaid, 'ม.86/4']);
    // The XML's sequential number is not printed on the paper form (observation for the owner).
    const printsEtNumber = has(pdf, subs.accepted!.invoiceNumber as string);
    // Nothing moved: same submission row, same payment, no RD traffic, no audit entries.
    const after = { submission: await loadSubmission(subs.accepted!.id), payment: await loadPayment(row.id), rdCalls: rd.calls.length, audits: await auditActions(subs.accepted!.id) };
    expect({ status: after.submission.status, signed: sha256(after.submission.signedXml as string), updatedAt: after.submission.updatedAt.toISOString(), payment: after.payment, rdCalls: after.rdCalls, audits: after.audits })
      .toEqual({ status: before.submission.status, signed: sha256(before.submission.signedXml as string), updatedAt: before.submission.updatedAt.toISOString(), payment: before.payment, rdCalls: before.rdCalls, audits: before.audits });
    // Same document for every allowed role, rendered again (jsPDF stamps a creation date, so compare content).
    const rendersFor = async (session: Session) => parsePdf(bodyBuffer(await invoicePdf(session, row.id)));
    const sameContent = (a: ParsedPdf, b: ParsedPdf) => a.pages.map((p) => p.lines.join('\n')).join('\f') === b.pages.map((p) => p.lines.join('\n')).join('\f');
    expect(sameContent(pdf, await rendersFor(financeManager))).toBe(true);
    expect(sameContent(pdf, await rendersFor(accountant))).toBe(true);
    const artifacts = [
      saveArtifact(DOMAIN, `tax-invoice-${contractA.contractNumber}-1.pdf`, bytes).relativePath,
      saveArtifact(DOMAIN, `tax-invoice-${contractA.contractNumber}-1.pdf.json`, JSON.stringify({ payment: row, submission: { id: subs.accepted!.id, status: subs.accepted!.status, invoiceNumber: subs.accepted!.invoiceNumber }, pdfNumber, printsEtNumber, headers: { contentType: response.headers['content-type'], contentDisposition: response.headers['content-disposition'] }, sha256: sha256(bytes), ...pdfSummary(pdf) }, null, 2)).relativePath,
    ];
    recordScenario(DOMAIN, scenario({ id: `${DOMAIN}/pdf-matches-source`, title: 'GET /e-tax/invoices/:paymentId/pdf: one A4 page, THSarabunPSK 18/16/12 pt, issuer = FINANCE entity, buyer/tax id/address = customer row, amounts = Payment.amountPaid/vatAmount, Thai Buddhist date = paidDate; download leaves submission/payment/audit/RD untouched; identical content for OWNER/FM/ACCOUNTANT', routes: ['GET /api/e-tax/invoices/:paymentId/pdf'], artifacts, notes: `Observation: the PDF prints its own number ${pdfNumber} (payment-derived) while the XML carries ${subs.accepted!.invoiceNumber} — the ET number ${printsEtNumber ? 'appears' : 'does not appear'} on the paper form; one tax invoice with two numbers is for the owner/CPA to decide. Observation: Content-Disposition names the file receipt-<paymentId>.pdf; the web page renames it tax-invoice-<contract>-<installment>.pdf. Amounts print without thousands separators (1416.66)` }));
  });

  it('long buyer name and address: the invoice continues onto a second A4 page without losing text, totals and footer stay together on the last page', async () => {
    const row = paid.L1;
    const response = await invoicePdf(owner, row.id);
    const bytes = bodyBuffer(response);
    const pdf = await parsePdf(bytes);
    expect(pdf.pageCount).toBeGreaterThanOrEqual(2);
    expect(pdf.pages.every(isA4)).toBe(true);
    expect(pdf.fonts.every((font) => font.startsWith(DOCUMENT_STYLE.pdfFontFamily))).toBe(true);
    for (const page of pdf.pages) expect({ page: page.index, lines: page.lines.length }).toMatchObject({ page: page.index, lines: expect.any(Number) });
    expect(pdf.pages.every((page) => page.lines.length >= 3)).toBe(true);
    // Every 30-character slice of the address survives the wrap (order-insensitive, position-insensitive).
    const folded = foldThai(pdf.pages.map(pageText).join('\n'));
    const address = foldThai(longCustomer.address);
    const missing: string[] = [];
    for (let at = 0; at < address.length; at += 30) { const slice = address.slice(at, at + 30); if (slice.length >= 12 && !folded.includes(slice)) missing.push(slice); }
    expect(missing).toEqual([]);
    expect(has(pdf, longCustomer.name)).toBe(true);
    const last = pdf.pageCount;
    expect(pageContaining(pdf, 'ราคาก่อนภาษีมูลค่าเพิ่ม')).toBe(last);
    expect(pageContaining(pdf, 'รวมทั้งสิ้น')).toBe(last);
    expect(pageContaining(pdf, 'ม.86/4')).toBe(last);
    expectAll(pdf, [row.base, row.vatAmount, row.amountPaid, `อ้างอิงสัญญา: ${contractLong.contractNumber}`, longCustomer.nationalId]);
    // The title block (BESTCHOICE / TAX INVOICE / เลขที่) is drawn once; autoTable repeats only the party-table head row.
    const headerOnContinuation = pdf.pages.slice(1).some((page) => page.text.includes('TAX INVOICE'));
    const partyHeadRepeated = pdf.pages.slice(1).some((page) => foldThai(page.text).includes(foldThai('ผู้ออกใบกำกับภาษี (ผู้ขาย)')));
    const artifacts = [
      saveArtifact(DOMAIN, `tax-invoice-${contractLong.contractNumber}-1.pdf`, bytes).relativePath,
      saveArtifact(DOMAIN, `tax-invoice-${contractLong.contractNumber}-1.pdf.json`, JSON.stringify({ payment: row, customer: { name: longCustomer.name, addressLength: longCustomer.address.length }, headerOnContinuation, partyHeadRepeated, ...pdfSummary(pdf) }, null, 2)).relativePath,
    ];
    recordScenario(DOMAIN, scenario({ id: `${DOMAIN}/continuation-pages`, title: `${pdf.pageCount}-page invoice for a ${longCustomer.address.length}-character registered address: every address slice present, no blank page, totals + ม.86/4 footer on the last page`, routes: ['GET /api/e-tax/invoices/:paymentId/pdf'], artifacts, notes: `Observation: continuation pages carry ${headerOnContinuation ? 'the' : 'no'} document title/number block and no page numbering (jspdf-autotable flow${partyHeadRepeated ? '; the party-table head row repeats' : ''}); the footer disclaimer is drawn once on the last page — a multi-page ใบกำกับภาษี without เลขที่ on later pages is for the owner/CPA to judge` }));
  });

  it('authorization on the PDF route: no token 401, BM/SALES 403, unknown or unpaid payment 404, wrong company 200 for cross-company roles; the ACCEPTED gate lives in the web page only', async () => {
    await invoicePdf(null, paid.A1.id, 401);
    await invoicePdf(branchManagerA, paid.A1.id, 403);
    await invoicePdf(salesA, paid.A1.id, 403);
    await invoicePdf(owner, '00000000-0000-4000-8000-000000000000', 404);
    const unpaid = await invoicePdf(owner, contractA.installments[2].paymentId, 404);
    expect(String(unpaid.body.message)).toBe('ไม่พบรายการชำระเงิน');
    // PENDING (never signed) and never-generated payments still render from the API — the ACCEPTED check is only in ETaxPage.
    const pending = await invoicePdf(owner, paid.A2.id, 200);
    const noSubmission = await invoicePdf(owner, paid.B1.id, 200);
    const b1 = await parsePdf(bodyBuffer(noSubmission));
    const finance = await h.prisma.companyInfo.findFirstOrThrow({ where: { companyCode: 'FINANCE' } });
    expectAll(b1, [finance.nameTh, `อ้างอิงสัญญา: ${contractB.contractNumber}`]);
    // Tampered token: audience/signature checked by the real strategy.
    await ok(h.client({ token: `${owner.token.slice(0, -4)}AAAA` }).get(`/e-tax/invoices/${paid.A1.id}/pdf`), 401, 'tampered token');
    const artifact = saveArtifact(DOMAIN, 'authorization.json', JSON.stringify({ pendingStatus: pending.status, noSubmissionStatus: noSubmission.status, unpaid: unpaid.body }, null, 2)).relativePath;
    recordScenario(DOMAIN, scenario({ id: `${DOMAIN}/authorization`, title: 'PDF route: 401 without/with tampered token, 403 BRANCH_MANAGER and SALES (RolesGuard), 404 unknown id and unpaid installment (same message, no enumeration); PENDING and never-generated payments still download for cross-company roles', routes: ['GET /api/e-tax/invoices/:paymentId/pdf'], renderer: 'none', artifacts: [artifact], notes: 'Observation: the ACCEPTED gate is enforced only by ETaxPage (button hidden); the API serves the paper form for any PAID VAT payment. Observation: ETaxService branch scoping for BRANCH_MANAGER/SALES is unreachable because RolesGuard rejects those roles first. Issuer is always the FINANCE entity even for a SHOP-branch contract' }));
  });

  it('no outbound transport was used by the e-Tax flows (only the recorded LINE receipts of the bookings); the only RD traffic is the scripted lifecycle', () => {
    expect(h.external.calls.length).toBe(outboundAfterBookings);
    expect(h.external.calls.every((call) => call.channel === 'line' && call.recipient.startsWith('TEST-NOT-SENT-'))).toBe(true);
    expect(rd.calls.map((call) => call.op)).toEqual(['ping', 'submit', 'checkStatus', 'checkStatus', 'submit']);
    const artifact = saveArtifact(DOMAIN, 'outbound.json', JSON.stringify({ recordedDuringBookings: h.external.calls, rd: rd.calls }, null, 2)).relativePath;
    recordScenario(DOMAIN, scenario({ id: `${DOMAIN}/no-outbound`, title: `Outbound recorder: ${outboundAfterBookings} LINE receipt pushes recorded while booking (recipient TEST-NOT-SENT-…, never sent), nothing from generate/sign/submit/download; RD spy saw ping + 2 submits + 2 status checks`, routes: [], renderer: 'none', artifacts: [artifact], notes: `synthetic RD endpoint ${rd.calls[0]?.endpoint}` }));
  });
});
