import Decimal from 'decimal.js';

/**
 * Draft hydration + dirty-check helpers for the RecordPaymentWizard DRAFT state
 * (mockup §11.1/§11.2 — DRAFT shows [ยกเลิก] [บันทึก] [ลงบัญชี] with an editable form).
 *
 * Why the fingerprint matters: `POST /payments/:id/post-draft` posts the STORED
 * draft and keeps `draft.createdById` as the recorder (maker) so the 4-eyes SoD
 * guard (waiver approver ≠ recorder) still holds when the approver is the one
 * clicking ลงบัญชี. Blindly re-saving before every post would flip the maker to
 * the poster and break that flow — so ลงบัญชี only saves-then-posts when the
 * form actually diverged from the hydrated draft.
 */

export type WizardMethod = 'CASH' | 'TRANSFER' | 'QR' | 'CARD';

/** Shape of GET /payments/draft/:paymentId (PaymentDraft row, Decimals serialized). */
export interface PaymentDraftRow {
  id: string;
  /** Bumped by every upsert — the wizard re-hydrates when id OR updatedAt changes
   *  (a failed post after a successful save leaves the same row id with new values). */
  updatedAt?: string;
  amount: string;
  paymentMethod: string;
  depositAccountCode: string | null;
  lateFee: string | null;
  lateFeeWaiverAmount: string | null;
  lateFeeWaiverReasonCode: string | null;
  waiverApproverId: string | null;
  consumeAdvance: boolean;
  paidDate: string | null;
  paymentCase: string | null;
  transactionRef: string | null;
  evidenceUrl: string | null;
  notes: string | null;
}

const API_TO_WIZARD_METHOD: Record<string, WizardMethod> = {
  CASH: 'CASH',
  BANK_TRANSFER: 'TRANSFER',
  QR_EWALLET: 'QR',
  CARD: 'CARD',
};

export function apiMethodToWizard(apiMethod: string): WizardMethod {
  return API_TO_WIZARD_METHOD[apiMethod] ?? 'CASH';
}

/**
 * The record flow stamps a fallback `transactionRef = <METHOD>-<Date.now()>` when
 * the cashier left the reference empty. That is machine noise, not user input —
 * filter it out on hydration so the reference field comes back empty.
 */
export function isAutoGeneratedRef(ref: string | null | undefined): boolean {
  return !!ref && /^(CASH|BANK_TRANSFER|QR_EWALLET|CARD)-\d{10,}$/.test(ref);
}

/** Form values the wizard sets when a draft loads (all display-formatted strings). */
export interface DraftFormValues {
  amount: string;
  method: WizardMethod;
  depositAccountCode: string;
  lateFee: string;
  waiver: string;
  waiverReasonCode: string;
  waiverApproverId: string;
  consumeAdvance: boolean;
  /** BKK-local YYYY-MM-DD */
  paidDate: string;
  caseOverride: 'PARTIAL' | 'OVERPAY_ADVANCE' | null;
  referenceNumber: string;
  slipUrl: string;
  memo: string;
}

const bkkDateOf = (iso: string): string =>
  new Date(iso).toLocaleDateString('en-CA', { timeZone: 'Asia/Bangkok' });

const money2 = (s: string | null | undefined): string => {
  try {
    return new Decimal(s || 0).toFixed(2);
  } catch {
    return '0.00';
  }
};

export function draftToFormValues(
  draft: PaymentDraftRow,
  fallbacks: { lateFee: string; depositAccountCode: string; paidDate: string },
): DraftFormValues {
  const waiver = money2(draft.lateFeeWaiverAmount);
  const hasWaiver = new Decimal(waiver).gt(0);
  return {
    amount: money2(draft.amount),
    method: apiMethodToWizard(draft.paymentMethod),
    depositAccountCode: draft.depositAccountCode ?? fallbacks.depositAccountCode,
    lateFee: draft.lateFee != null ? money2(draft.lateFee) : fallbacks.lateFee,
    waiver: hasWaiver ? new Decimal(waiver).toString() : '0',
    // A waiver of 0 means the reason/approver rows are stale leftovers — drop them
    // so the fingerprint matches what buildPayload() would actually send.
    waiverReasonCode: hasWaiver ? draft.lateFeeWaiverReasonCode ?? '' : '',
    waiverApproverId: hasWaiver ? draft.waiverApproverId ?? '' : '',
    consumeAdvance: draft.consumeAdvance,
    paidDate: draft.paidDate ? bkkDateOf(draft.paidDate) : fallbacks.paidDate,
    caseOverride:
      draft.paymentCase === 'PARTIAL' || draft.paymentCase === 'OVERPAY_ADVANCE'
        ? draft.paymentCase
        : null,
    referenceNumber: isAutoGeneratedRef(draft.transactionRef) ? '' : draft.transactionRef ?? '',
    slipUrl: draft.evidenceUrl ?? '',
    memo: draft.notes ?? '',
  };
}

/**
 * Canonical fingerprint for the ลงบัญชี dirty-check. Money fields are normalized
 * to 2dp so '1515.8' vs '1515.80' compares equal; free-text is trimmed.
 */
export function draftFingerprint(v: DraftFormValues): string {
  const hasWaiver = (() => {
    try {
      return new Decimal(v.waiver || 0).gt(0);
    } catch {
      return false;
    }
  })();
  return JSON.stringify({
    amount: money2(v.amount),
    method: v.method,
    account: v.depositAccountCode,
    lateFee: money2(v.lateFee),
    waiver: money2(v.waiver),
    waiverReasonCode: hasWaiver ? v.waiverReasonCode : '',
    waiverApproverId: hasWaiver ? v.waiverApproverId : '',
    consumeAdvance: v.consumeAdvance,
    paidDate: v.paidDate,
    caseOverride: v.caseOverride,
    referenceNumber: v.referenceNumber.trim(),
    slipUrl: v.slipUrl,
    memo: v.memo.trim(),
  });
}
