import { randomUUID } from 'crypto';
import { mkdtemp, rm, readdir } from 'fs/promises';
import { tmpdir } from 'os';
import { join } from 'path';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from '../src/prisma/prisma.service';
import { StorageService } from '../src/modules/storage/storage.service';
import { ChatWorkAccessService } from '../src/modules/staff-chat/services/chat-work-access.service';
import { ChatLibraryService } from '../src/modules/staff-chat/services/chat-library.service';
import { readLimited } from '../src/modules/credit-check/services/media-fetch.util';
import type { ChatWorkActor } from '@installment/shared';
if (!process.env.DATABASE_URL?.includes('/bc_chat_credit_test?host=/tmp/bc-chat-credit.')) throw new Error('Use disposable harness');
describe('Private scoped chat library with real bytes', () => {
  const db = new PrismaService();
  let root: string, storage: StorageService, svc: ChatLibraryService;
  let owner: ChatWorkActor, sales: ChatWorkActor, other: ChatWorkActor;
  const scope = { company: 'SHOP' as const };
  const bytes = Buffer.from([0xff, 0xd8, 0xff, 0xe0, 1, 2, 3]);
  const file = (name = 'สินค้า.jpg') => ({ originalname: name, buffer: bytes, mimetype: 'image/jpeg' } as Express.Multer.File);
  beforeAll(async () => {
    root = await mkdtemp(join(tmpdir(), 'chat-library-'));
    storage = new StorageService(new ConfigService({ STORAGE_LOCAL_DIR: root, NODE_ENV: 'test' }));
    svc = new ChatLibraryService(db, new ChatWorkAccessService(db), storage);
    const branch = await db.branch.create({ data: { name: 'Cloud own' } });
    const foreign = await db.branch.create({ data: { name: 'Cloud other' } });
    const staff = (role: 'OWNER' | 'SALES', branchId: string) => db.user.create({ data: { email: `${randomUUID()}@cloud.invalid`, name: role, role, branchId, password: 'unused', accessibleCompanies: ['SHOP', 'FINANCE'] } });
    owner = await staff('OWNER', branch.id); sales = await staff('SALES', branch.id); other = await staff('SALES', foreign.id);
    await db.systemConfig.upsert({ where: { key: 'chat_cloud_library_enabled' }, create: { key: 'chat_cloud_library_enabled', value: 'true' }, update: { value: 'true', deletedAt: null } });
  });
  afterAll(async () => { await db.$disconnect(); await rm(root, { recursive: true, force: true }); });
  it('stores private bytes, searches/paginates and hides keys; retry is idempotent and changed payload conflicts', async () => {
    const folder = await svc.createFolder(owner, scope, { name: 'โปรโมชั่น' });
    const input = { requestKey: randomUUID(), folderId: folder.id };
    const a = await svc.upload(owner, scope, input, file());
    expect(a).not.toHaveProperty('key');
    expect((await svc.upload(owner, scope, input, file())).id).toBe(a.id);
    await expect(svc.upload(owner, scope, input, file('เปลี่ยน.jpg'))).rejects.toThrow();
    const list = await svc.files(sales, { ...scope, folderId: folder.id, search: 'สินค้า', page: 1, limit: 1 });
    expect(list.total).toBe(1); expect(list.data[0].id).toBe(a.id);
    expect((await svc.files(sales, { ...scope, folderId: folder.id, page: 2, limit: 1 })).data).toEqual([]);
    expect(await readLimited((await svc.content(sales, scope, a.id)).stream)).toEqual(bytes);
    await expect(svc.content(sales, { company: 'FINANCE' }, a.id)).rejects.toThrow();
  });
  it('enforces current branch/grants and archived folder/file at list, upload and content boundaries', async () => {
    const folder = await svc.createFolder(sales, scope, { name: 'เฉพาะสาขา' });
    const a = await svc.upload(sales, scope, { requestKey: randomUUID(), folderId: folder.id }, file());
    await expect(svc.content(other, scope, a.id)).rejects.toThrow();
    await expect(svc.upload(other, scope, { requestKey: randomUUID(), folderId: folder.id }, file())).rejects.toThrow();
    expect((await svc.folders(other, scope)).data.some(f => f.id === folder.id)).toBe(false);
    await db.user.update({ where: { id: sales.id }, data: { accessibleCompanies: ['FINANCE'] } });
    await expect(svc.content(sales, scope, a.id)).rejects.toThrow();
    await db.user.update({ where: { id: sales.id }, data: { accessibleCompanies: ['SHOP', 'FINANCE'] } });
    await db.chatLibraryFolder.update({ where: { id: folder.id }, data: { deletedAt: new Date() } });
    await expect(svc.content(owner, scope, a.id)).rejects.toThrow();
    await expect(svc.upload(owner, scope, { requestKey: randomUUID(), folderId: folder.id }, file())).rejects.toThrow();
    const b = await svc.upload(owner, scope, { requestKey: randomUUID() }, file());
    await db.chatLibraryFile.update({ where: { id: b.id }, data: { deletedAt: new Date() } });
    await expect(svc.content(owner, scope, b.id)).rejects.toThrow();
  });
  it('rejects spoofed HTML and cleans uploaded objects on persistence failure and storage failure', async () => {
    await expect(svc.upload(owner, scope, { requestKey: randomUUID() }, { ...file(), buffer: Buffer.from('<html>') })).rejects.toThrow();
    const count = async () => (await readdir(root, { recursive: true })).filter(x => x.endsWith('.jpg')).length;
    const before = await count();
    const spy = jest.spyOn(db, '$transaction').mockRejectedValueOnce(new Error('DB unavailable'));
    await expect(svc.upload(owner, scope, { requestKey: randomUUID() }, file())).rejects.toThrow('DB unavailable');
    spy.mockRestore(); expect(await count()).toBe(before);
    const upload = jest.spyOn(storage, 'upload').mockRejectedValueOnce(new Error('storage unavailable'));
    await expect(svc.upload(owner, scope, { requestKey: randomUUID() }, file())).rejects.toThrow('storage unavailable');
    upload.mockRestore(); expect(await count()).toBe(before);
  });
});
